# SPDX-FileCopyrightText: Chris Wilson <christopher.david.wilson@gmail.com>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.143.0"
