# SPDX-FileCopyrightText: 2024 Chris Wilson <christopher.david.wilson@gmail.com>
#
# SPDX-License-Identifier: MIT

[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.138.0"
