# SPDX-FileCopyrightText: Chris Wilson <christopher.david.wilson@gmail.com>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

version = 1
SPDX-PackageName = "cdwilson.dev"
SPDX-PackageSupplier = "Chris Wilson <christopher.david.wilson@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/cdwilson/cdwilson.dev"

[[annotations]]
path = ["**.md", "**.png", "**.jpg", "**.jpeg", "**.webp", "**.ico", "**.drawio", "**.monopic", "**.gif", "**.svg", "**.html"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Chris Wilson <christopher.david.wilson@gmail.com>"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ["static/site.webmanifest", "**.scss", "**.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Chris Wilson <christopher.david.wilson@gmail.com>"
SPDX-License-Identifier = "MIT or Apache-2.0"
